import type { CapabilityDefinition } from "../types.ts";

/**
 * Canonical capability registry.
 *
 * Single source of truth for Blaster domain capabilities across Convex,
 * Hono HTTP, the shared client, CLI, and MCP.
 */
export const CAPABILITY_REGISTRY: readonly CapabilityDefinition[] = [
  // --- Number Pools ---
  {
    id: "pools.list",
    resource: "pools",
    operation: "listPools",
    title: "List number pools",
    description: "List number pools with rate state, active sender counts, and next dispatch times.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.pool.queries.listPools",
      http: "GET /api/pools",
      client: "listPools",
      cli: "blaster pools list",
      mcp: "blaster_list_pools",
    },
  },
  {
    id: "pools.get",
    resource: "pools",
    operation: "getPool",
    title: "Get pool details",
    description: "Read one pool with numbers in sequential dispatch order and per-number rate state.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.pool.queries.getPool",
      http: "GET /api/pools/:id",
      client: "getPool",
      cli: "blaster pools show",
      mcp: "blaster_get_pool",
    },
  },
  {
    id: "pools.create",
    resource: "pools",
    operation: "createPool",
    title: "Create number pool",
    description: "Create a number pool with minimum dispatch spacing and daily send ceiling per number.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.pool.mutations.createPool",
      http: "POST /api/pools",
      client: "createPool",
      cli: "blaster pools create",
      mcp: "blaster_create_pool",
    },
  },
  {
    id: "pools.addNumber",
    resource: "pools",
    operation: "addPoolNumber",
    title: "Add number to pool",
    description: "Assign an owned E.164 phone number to a pool or reactivate a removed membership.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.pool.mutations.assignNumber",
      http: "POST /api/pools/:id/numbers",
      client: "addPoolNumber",
      cli: "blaster pools add-number",
      mcp: "blaster_add_pool_number",
    },
  },
  {
    id: "pools.removeNumber",
    resource: "pools",
    operation: "removePoolNumber",
    title: "Remove number from pool",
    description: "Soft-remove a sending number from a pool to preserve send history and in-flight resolutions.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.pool.mutations.removeNumber",
      http: "DELETE /api/pools/:id/numbers/:phoneNumber",
      client: "removePoolNumber",
      cli: "blaster pools remove-number",
      mcp: "blaster_remove_pool_number",
    },
  },
  {
    id: "pools.reorder",
    resource: "pools",
    operation: "reorderPoolNumbers",
    title: "Reorder pool numbers",
    description: "Set the sequential dispatch order of phone numbers assigned to a pool.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.pool.mutations.reorderNumbers",
      http: "PUT /api/pools/:id/numbers",
      client: "reorderPoolNumbers",
      cli: "blaster pools reorder",
      mcp: "blaster_reorder_pool",
    },
  },

  // --- Sequences (Committed) ---
  {
    id: "sequences.list",
    resource: "sequences",
    operation: "listSequences",
    title: "List outreach sequences",
    description: "List outreach sequences, newest first, with step counts, statuses, and assigned pools.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli"],
    mappings: {
      convex: "api.sequence.queries.listSequences",
      http: "GET /api/sequences",
      client: "listSequences",
      cli: "blaster sequence list",
    },
  },
  {
    id: "sequences.get",
    resource: "sequences",
    operation: "getSequence",
    title: "Get outreach sequence",
    description: "Read a single sequence with its step configuration, sender options, and status.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli"],
    mappings: {
      convex: "api.sequence.queries.getSequence",
      http: "GET /api/sequences/:id",
      client: "getSequence",
      cli: "blaster sequence show",
    },
  },
  {
    id: "sequences.create",
    resource: "sequences",
    operation: "createSequence",
    title: "Create outreach sequence",
    description: "Register a validated multi-step outreach sequence directly in Convex with steps and options.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.mutations.createSequence",
      http: "POST /api/sequences",
      client: "registerSequence",
      cli: "blaster sequence new",
      mcp: "blaster_register_sequence",
    },
  },
  {
    id: "sequences.activate",
    resource: "sequences",
    operation: "activateSequence",
    title: "Activate outreach sequence",
    description: "Activate a sequence for sending once steps and active sender/pool are validated.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.mutations.setSequenceStatus",
      http: "POST /api/sequences/:id/activate",
      client: "activateSequence",
      cli: "blaster sequence activate",
      mcp: "blaster_activate_sequence",
    },
  },
  {
    id: "sequences.delete",
    resource: "sequences",
    operation: "deleteSequence",
    title: "Delete outreach sequence",
    description: "Delete an outreach sequence and its step records from Convex.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.mutations.deleteSequence",
      http: "DELETE /api/sequences/:id",
      client: "deleteSequence",
      cli: "blaster sequence rm",
      mcp: "blaster_delete_sequence",
    },
  },
  {
    id: "sequences.setPool",
    resource: "sequences",
    operation: "setSequencePool",
    title: "Assign pool to sequence",
    description: "Assign a number pool to a sequence for rotated delivery or clear the assignment.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.mutations.setSequencePool",
      http: "POST /api/sequences/:id/pool",
      client: "setSequencePool",
      cli: "blaster pools assign",
      mcp: "blaster_set_sequence_pool",
    },
  },
  {
    id: "sequences.enroll",
    resource: "sequences",
    operation: "enrollRecipients",
    title: "Enroll recipients into sequence",
    description: "Enroll prospects into a sequence from Twenty matching filter criteria, returning per-recipient outcomes.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.actions.enrollRecipients",
      http: "POST /api/sequences/:id/enroll",
      client: "enrollRecipients",
      cli: "blaster sequence enroll",
      mcp: "blaster_enroll_recipients",
    },
  },
  {
    id: "sequences.validate",
    resource: "sequences",
    operation: "validateSequence",
    title: "Validate sequence draft",
    description: "Check a message sequence draft against domain rules and report all problems.",
    mutating: false,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "POST /api/sequences/validate",
      cli: "blaster sequence validate",
      mcp: "blaster_validate_sequence",
    },
  },
  {
    id: "sequences.preview",
    resource: "sequences",
    operation: "previewSequence",
    title: "Preview sequence dispatch",
    description: "Dry run sequence steps against a recipient set to verify quiet hours and eligibility without sending.",
    mutating: false,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "POST /api/sequences/preview",
      cli: "blaster sequence preview",
      mcp: "blaster_preview_sequence",
    },
  },

  // --- Sequence Drafts (Lifecycle) ---
  {
    id: "sequences.drafts.list",
    resource: "sequenceDrafts",
    operation: "listSequenceDrafts",
    title: "List sequence drafts",
    description: "List unfinished resumable sequence builder drafts checkpointed in Convex.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.drafts.listSequenceDrafts",
      http: "GET /api/sequence-drafts",
      client: "listSequenceDrafts",
      cli: "blaster sequence drafts",
      mcp: "blaster_list_sequence_drafts",
    },
  },
  {
    id: "sequences.drafts.get",
    resource: "sequenceDrafts",
    operation: "getSequenceDraft",
    title: "Get sequence draft",
    description: "Get details of an unfinished resumable sequence draft by ID.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "mcp"],
    mappings: {
      convex: "api.sequence.drafts.getSequenceDraft",
      http: "GET /api/sequence-drafts/:id",
      client: "getSequenceDraft",
      mcp: "blaster_get_sequence_draft",
    },
  },
  {
    id: "sequences.drafts.save",
    resource: "sequenceDrafts",
    operation: "saveSequenceDraft",
    title: "Save sequence draft",
    description: "Checkpoint interactive wizard progress into Convex sequenceDrafts table.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.drafts.saveSequenceDraft",
      http: "POST /api/sequence-drafts",
      client: "saveSequenceDraft",
      cli: "blaster sequence save-draft",
      mcp: "blaster_save_sequence_draft",
    },
  },
  {
    id: "sequences.drafts.discard",
    resource: "sequenceDrafts",
    operation: "discardSequenceDraft",
    title: "Discard sequence draft",
    description: "Delete an uncommitted builder draft from Convex without creating a live sequence.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.drafts.discardSequenceDraft",
      http: "DELETE /api/sequence-drafts/:id",
      client: "discardSequenceDraft",
      cli: "blaster sequence discard-draft",
      mcp: "blaster_discard_sequence_draft",
    },
  },
  {
    id: "sequences.drafts.commit",
    resource: "sequenceDrafts",
    operation: "commitSequenceDraft",
    title: "Commit sequence draft",
    description: "Validate and commit a completed draft into a live sequence in Convex and remove the draft row.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.sequence.drafts.commitSequenceDraft",
      http: "POST /api/sequence-drafts/:id/commit",
      client: "commitSequenceDraft",
      cli: "blaster sequence commit-draft",
      mcp: "blaster_commit_sequence_draft",
    },
  },

  // --- Suppressions ---
  {
    id: "numbers.attach",
    resource: "numbers",
    operation: "attachNumber",
    title: "Attach a number so it can send",
    description: "Attach a number to its Telnyx account, state, messaging profile and pool, and report what it still needs before it can send.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.phoneNumbers.mutations.attach",
      http: "POST /api/numbers/attach",
      client: "attachNumber",
      cli: "blaster numbers attach",
      mcp: "blaster_attach_number",
    },
  },
  {
    id: "accounts.list",
    resource: "accounts",
    operation: "listAccounts",
    title: "List Telnyx accounts",
    description: "List Telnyx accounts with status and whether each API key is configured. Never returns a key.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.telnyxAccounts.mutations.listAccounts",
      http: "GET /api/accounts",
      client: "listAccounts",
      cli: "blaster accounts list",
      mcp: "blaster_list_accounts",
    },
  },
  {
    id: "accounts.set",
    resource: "accounts",
    operation: "setAccount",
    title: "Register or update a Telnyx account",
    description: "Register a Telnyx account or change its label or status (active, burned, disabled).",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.telnyxAccounts.mutations.registerAccount",
      http: "POST /api/accounts",
      client: "setAccount",
      cli: "blaster accounts add|burn|disable|activate",
      mcp: "blaster_set_account",
    },
  },
  {
    id: "accounts.assign",
    resource: "accounts",
    operation: "assignNumberAccount",
    title: "Assign a number to a Telnyx account",
    description: "Attach a sender number to a Telnyx account, or return it to the default account.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.telnyxAccounts.mutations.setNumberAccount",
      http: "POST /api/accounts/assign",
      client: "assignNumberAccount",
      cli: "blaster accounts assign",
      mcp: "blaster_assign_number_account",
    },
  },
  {
    id: "suppressions.list",
    resource: "suppressions",
    operation: "listSuppressions",
    title: "List suppressions",
    description: "List durable per-person do-not-contact suppressions holding across all sequences.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.suppressions.mutations.listSuppressions",
      http: "GET /api/suppressions",
      client: "listSuppressions",
      cli: "blaster suppress list",
      mcp: "blaster_list_suppressions",
    },
  },
  {
    id: "suppressions.set",
    resource: "suppressions",
    operation: "setSuppression",
    title: "Record or lift suppression",
    description: "Record a manual do-not-contact suppression for an E.164 peer, or lift one.",
    mutating: true,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.suppressions.mutations.suppress",
      http: "POST /api/suppressions",
      client: "setSuppression",
      cli: "blaster suppress add|remove",
      mcp: "blaster_set_suppression",
    },
  },

  // --- Conversations & Inbox ---
  {
    id: "conversations.list",
    resource: "conversations",
    operation: "listConversations",
    title: "List SMS conversations",
    description: "List SMS conversation threads ordered by newest activity with optional filter by sender or campaign.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.conversations.queries.listConversations",
      http: "GET /api/conversations",
      client: "listConversations",
      cli: "blaster inbox list",
      mcp: "blaster_list_conversations",
    },
  },
  {
    id: "conversations.persons",
    resource: "conversations",
    operation: "listConversationPersons",
    title: "List conversations grouped by person",
    description: "List SMS conversations folded one row per person with sender numbers and campaign unions.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.conversations.queries.listConversations",
      http: "GET /api/conversations?groupBy=person",
      client: "listConversationPersons",
      cli: "blaster inbox list --person",
      mcp: "blaster_list_conversation_persons",
    },
  },
  {
    id: "conversations.read",
    resource: "conversations",
    operation: "getConversationMessages",
    title: "Read conversation messages",
    description: "Read every message in one conversation thread, oldest first, with delivery statuses.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.conversations.queries.conversationMessages",
      http: "GET /api/conversations/:id/messages",
      client: "conversationMessages",
      cli: "blaster inbox show",
      mcp: "blaster_get_messages",
    },
  },

  // --- Messaging & Profiles ---
  {
    id: "messaging.send",
    resource: "messaging",
    operation: "sendMessage",
    title: "Send single SMS",
    description: "Send one SMS through Telnyx on the messaging profile registered for the recipient country.",
    mutating: true,
    intendedSurfaces: ["http", "client", "cli", "mcp"],
    mappings: {
      http: "POST /api/messages/send",
      client: "sendMessage",
      cli: "blaster send",
      mcp: "blaster_send_message",
    },
  },
  {
    id: "messaging.profile",
    resource: "messaging",
    operation: "resolveMessagingProfile",
    title: "Resolve recipient messaging profile",
    description: "Determine which Telnyx messaging profile a recipient phone number maps to and why.",
    mutating: false,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "GET /api/messaging/profile",
      cli: "blaster profile",
      mcp: "blaster_messaging_profile",
    },
  },

  // --- Pipeline & Prospects ---
  {
    id: "pipeline.breakdown",
    resource: "pipeline",
    operation: "getPipelineBreakdown",
    title: "Pipeline conversion breakdown",
    description: "Read lead and call outcome counts, conversion rates, and active alert notifications.",
    mutating: false,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "GET /api/breakdown",
      cli: "blaster breakdown",
      mcp: "blaster_breakdown",
    },
  },
  {
    id: "prospects.list",
    resource: "prospects",
    operation: "listRecords",
    title: "List Twenty workspace records",
    description: "List records from a Twenty CRM object with keyset pagination.",
    mutating: false,
    intendedSurfaces: ["cli", "mcp"],
    mappings: {
      cli: "blaster prospects",
      mcp: "blaster_list_records",
    },
  },
  {
    id: "prospects.fields",
    resource: "prospects",
    operation: "listProspectFields",
    title: "List prospect filter fields",
    description: "Get the menu of filterable prospect fields introspected from Twenty CRM.",
    mutating: false,
    intendedSurfaces: ["http", "client"],
    mappings: {
      http: "GET /api/prospects/fields",
      client: "listProspectFields",
    },
  },
  {
    id: "prospects.search",
    resource: "prospects",
    operation: "searchProspects",
    title: "Search prospects by filter",
    description: "Search a page of prospects in Twenty CRM matching caller-supplied filter criteria.",
    mutating: false,
    intendedSurfaces: ["http", "client"],
    mappings: {
      http: "POST /api/prospects/search",
      client: "searchProspects",
    },
  },
  {
    id: "prospects.preview",
    resource: "prospects",
    operation: "previewProspectSend",
    title: "Preview prospect batch send",
    description: "Preview eligibility breakdown and recipient count for a filtered prospect batch send.",
    mutating: false,
    intendedSurfaces: ["http", "client"],
    mappings: {
      http: "POST /api/messages/preview",
      client: "previewProspectSend",
    },
  },
  {
    id: "prospects.batchSend",
    resource: "prospects",
    operation: "sendToProspects",
    title: "Batch send to prospects",
    description: "Execute batch SMS delivery to eligible prospects matching filter criteria with idempotency.",
    mutating: true,
    intendedSurfaces: ["http", "client"],
    mappings: {
      http: "POST /api/messages/batch-send",
      client: "sendToProspects",
    },
  },

  // --- Phone Inventory, Sync & Compliance ---
  {
    id: "numbers.search",
    resource: "numbers",
    operation: "searchNumbers",
    title: "Search available numbers",
    description: "Search Telnyx inventory for purchaseable phone numbers by country, type, and features.",
    mutating: false,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "GET /api/numbers/search",
      cli: "blaster numbers search",
      mcp: "blaster_search_numbers",
    },
  },
  {
    id: "numbers.purchase",
    resource: "numbers",
    operation: "purchaseNumbers",
    title: "Purchase phone numbers",
    description: "Purchase exact Telnyx phone numbers and mirror into Twenty agencyPhones.",
    mutating: true,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "POST /api/numbers/purchase",
      cli: "blaster numbers buy",
      mcp: "blaster_purchase_number",
    },
  },
  {
    id: "numbers.owned",
    resource: "numbers",
    operation: "listOwnedNumbers",
    title: "List owned Telnyx numbers",
    description: "List numbers currently provisioned and owned on the Telnyx account.",
    mutating: false,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "GET /api/numbers/owned",
      cli: "blaster numbers owned",
      mcp: "blaster_list_numbers",
    },
  },
  {
    id: "phones.list",
    resource: "phones",
    operation: "listAgencyPhones",
    title: "List agency phones",
    description: "List workspace phone numbers from Twenty agencyPhones.",
    mutating: false,
    intendedSurfaces: ["http", "client", "cli", "mcp"],
    mappings: {
      http: "GET /api/phones",
      client: "listSendingNumbers",
      cli: "blaster phones list",
      mcp: "blaster_list_numbers",
    },
  },
  {
    id: "phones.sync",
    resource: "phones",
    operation: "syncPhones",
    title: "Sync phones between Convex and Twenty",
    description: "Sync phone number rows bi-directionally between Convex purchase ledger and Twenty agencyPhones.",
    mutating: true,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "POST /api/phones/sync",
      cli: "blaster phones sync",
      mcp: "blaster_sync_phones",
    },
  },
  {
    id: "phones.compliance",
    resource: "phones",
    operation: "getPhoneCompliance",
    title: "Check phone 10DLC compliance",
    description: "Check 10DLC brand, campaign assignment, and carrier provisioning compliance snapshot.",
    mutating: false,
    intendedSurfaces: ["convex", "http", "client", "cli", "mcp"],
    mappings: {
      convex: "api.phoneNumbers.queries.getCompliance",
      http: "GET /api/phones/:number/compliance",
      client: "getPhoneCompliance",
      cli: "blaster phones compliance",
      mcp: "blaster_check_phone_compliance",
    },
  },

  // --- Platform & Auth ---
  {
    id: "env.describe",
    resource: "env",
    operation: "describeEnv",
    title: "Describe environment manifest",
    description: "Audit required and configured environment variables and missing country profile coverage.",
    mutating: false,
    intendedSurfaces: ["http", "cli", "mcp"],
    mappings: {
      http: "GET /api/env",
      cli: "blaster env",
      mcp: "blaster_env",
    },
  },
  {
    id: "auth.login",
    resource: "auth",
    operation: "login",
    title: "Operator web login",
    description: "Authenticate operator session via PKCE browser authorization flow with Twenty OAuth.",
    mutating: true,
    intendedSurfaces: ["cli"],
    mappings: {
      cli: "blaster login",
    },
  },
  {
    id: "auth.logout",
    resource: "auth",
    operation: "logout",
    title: "Operator logout",
    description: "Clear stored operator session tokens.",
    mutating: true,
    intendedSurfaces: ["cli"],
    mappings: {
      cli: "blaster logout",
    },
  },
  {
    id: "auth.whoami",
    resource: "auth",
    operation: "whoami",
    title: "Operator whoami",
    description: "Verify stored operator session validity and show identity claims.",
    mutating: false,
    intendedSurfaces: ["cli"],
    mappings: {
      cli: "blaster whoami",
    },
  },
] as const;
