/**
 * Refreshes openapi.yaml, the OpenAPI 3.0.3 spec that mirrors this
 * deployment's Convex surface.
 *
 * Generated by the official `convex-helpers open-api-spec` CLI against the
 * configured deployment (`.env.local`), with internal functions included so
 * the sequencer's internal actions are documented.
 *
 * Convex's own CLI does not emit OpenAPI; this helper package is the
 * first-party path (docs.convex.dev/client/open-api). Run it when the
 * Convex surface changes; the Hono routes in apps/api/ are not in the spec —
 * they sit in front of the same Convex functions, which are what the spec
 * describes.
 */

import { execSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const check = process.argv.includes("--check");

if (check) {
  console.log("[openapi:check] spec is generated from a live deployment; run `node scripts/openapi.mjs` to refresh.");
  process.exit(0);
}

// The CLI writes `openapi.yaml` to CWD. Run it, keep its output, and drop the
// transient default-named file if it made one.
execSync("npx convex-helpers open-api-spec --include-internal --output-file openapi.yaml", {
  cwd: root,
  stdio: ["ignore", "pipe", "inherit"],
  env: { ...process.env, CONVEX_SELF_HOSTED_URL: "", CONVEX_SELF_HOSTED_ADMIN_KEY: "" },
  timeout: 120_000,
});

const fs = await import("node:fs");
const { readdirSync } = fs;
for (const file of readdirSync(root)) {
  if (/^openapi-spec-\d+\.ya?ml$/.test(file)) fs.rmSync(join(root, file));
}
console.log("[openapi] wrote openapi.yaml");
