import { makeFunctionReference } from "convex/server";

/**
 * Typed function references for the test tree.
 *
 * `convex-test`'s `t.query`/`t.mutation` take a `FunctionReference`, and the
 * string form only typechecks with a `never` cast that then makes the result
 * `never` too — which is how a test can silently assert nothing. These are real
 * references with declared argument and return types, so a wrong argument is a
 * compile error and the result carries its shape.
 *
 * The `_generated/api` module cannot be imported here: it is regenerated by
 * `convex dev` and this tree typechecks without a deployment. A
 * `makeFunctionReference` over the module path is the documented way to name a
 * function without codegen, and the path is still checked by the string.
 */

export const ref = {
  createPool: makeFunctionReference<"mutation", { name: string; minSpacingMs?: number; dailyCapPerNumber?: number }, string>(
    "pool/mutations:createPool",
  ),
  assignNumber: makeFunctionReference<"mutation", { poolId: string; phoneNumber: string; order?: number }, unknown>(
    "pool/mutations:assignNumber",
  ),
  removeNumber: makeFunctionReference<"mutation", { poolId: string; phoneNumber: string }, unknown>(
    "pool/mutations:removeNumber",
  ),
  reorderNumbers: makeFunctionReference<"mutation", { poolId: string; order: string[] }, unknown>(
    "pool/mutations:reorderNumbers",
  ),
  consumeSender: makeFunctionReference<
    "mutation",
    { poolId: string; order: number; now?: number },
    { sender: { phoneNumber: string; messagingProfileId?: string; order: number } | null; soonestNextAvailableAt: number | null }
  >("pool/mutations:consumeSender"),
  getPool: makeFunctionReference<
    "query",
    { poolId: string },
    | {
        name: string;
        status: string;
        cursor: number;
        activeNumberCount: number;
        numbers: Array<{ order: number; status: string; sentToday: number; phoneNumber: string }>;
      }
    | null
  >("pool/queries:getPool"),
  availableSender: makeFunctionReference<
    "query",
    { poolId: string; now?: number },
    { sender: { phoneNumber: string; messagingProfileId?: string; order: number } | null; soonestNextAvailableAt: number | null }
  >("pool/queries:availableSender"),
  getPhoneNumber: makeFunctionReference<"query", { phoneNumber: string }, { phoneNumber: string } | null>(
    "phoneNumbers/queries:getPhoneNumber",
  ),
  recordInboundMessage: makeFunctionReference<
    "mutation",
    {
      from: string;
      to: string;
      body: string;
      telnyxMessageId?: string;
      providerEventId?: string;
      receivedAt?: number;
      optedOut?: boolean;
    },
    {
      status: "stored" | "duplicate";
      conversationId: string;
      messageId: string;
      stoppedEnrollments: Array<{ enrollmentId: string; sequenceId: string; status: string }>;
      suppressed?: boolean;
    }
  >("conversations/mutations:recordInboundMessage"),
  enroll: makeFunctionReference<
    "mutation",
    {
      sequenceId: string;
      recipientId: string;
      to?: string;
      country?: string;
      ownerMemberId?: string;
      doNotContact?: boolean;
    },
    string
  >("sequence/mutations:enroll"),
  isPeerSuppressed: makeFunctionReference<"query", { peer: string }, boolean>("suppressions/mutations:isPeerSuppressed"),
  suppress: makeFunctionReference<
    "mutation",
    { peer: string; reason?: string; source?: "inbound-opt-out" | "manual" },
    { peer: string; created: boolean }
  >("suppressions/mutations:suppress"),
  lift: makeFunctionReference<"mutation", { peer: string }, { peer: string; lifted: boolean }>(
    "suppressions/mutations:lift",
  ),
  listConversations: makeFunctionReference<
    "query",
    { limit?: number; number?: string; campaign?: string; withCampaign?: boolean; groupBy?: "person" },
    Array<{
      phoneNumber: string;
      blasterNumbers: string[];
      conversationIds: string[];
      latestMessageAt: number;
      messageCount: number;
      campaignId: string | null;
      campaignGroup: "unassigned" | "multiple" | "one";
      candidateCampaignIds?: string[];
    }>
  >("conversations/queries:listConversations"),
} as const;

export const linkRef = makeFunctionReference<
  "mutation",
  { conversationId: string; prospectId: string; leadId?: string },
  { status: string; field?: string }
>("conversations/mutations:linkConversation");

export const inboundRef = makeFunctionReference<
  "mutation",
  { from: string; to: string; body: string; providerEventId?: string },
  { status: string; conversationId: string; prospectId: string | null; leadId: string | null }
>("conversations/mutations:recordInboundMessage");
